# Generated by Django 5.1 on 2025-12-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addressmodel',
            table='shop_addressmodel',
        ),
        migrations.AlterModelTable(
            name='carousel',
            table='shop_carousel',
        ),
        migrations.AlterModelTable(
            name='cart',
            table='shop_cart',
        ),
        migrations.AlterModelTable(
            name='category',
            table='shop_category',
        ),
        migrations.AlterModelTable(
            name='favourite',
            table='shop_favourite',
        ),
        migrations.AlterModelTable(
            name='order',
            table='shop_order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='shop_orderitem',
        ),
        migrations.AlterModelTable(
            name='otpverification',
            table='shop_otpverification',
        ),
        migrations.AlterModelTable(
            name='product',
            table='shop_product',
        ),
        migrations.AlterModelTable(
            name='supportissue',
            table='shop_supportissue',
        ),
    ]
