# Generated by Django 4.2.16 on 2026-01-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_productrating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['product'], name='product_rat_product_34f46e_idx'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['product', 'rating'], name='product_rat_product_96dfc4_idx'),
        ),
        migrations.AddIndex(
            model_name='productrating',
            index=models.Index(fields=['user', 'product'], name='product_rat_user_id_a341b9_idx'),
        ),
    ]
