# Generated by Django 4.2.16 on 2026-01-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_order_options_remove_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
