# Generated by Django 4.2.16 on 2026-03-11 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0011_product_product_image_2_product_product_image_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('label_pdf', models.FileField(blank=True, null=True, upload_to='shipping_labels/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='label_qrcodes/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_printed', models.BooleanField(default=False)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_label', to='Shop.order')),
                ('printed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Label',
                'verbose_name_plural': 'Shipping Labels',
                'ordering': ['-generated_at'],
            },
        ),
    ]
