# Generated by Django 5.1 on 2024-09-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0022_order_final_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='zipcode',
            field=models.CharField(max_length=10),
        ),
    ]
